
Imports BL

Public Class SelectBills

    Public CMPNAME As String = ""
    Public BILLNO As String = ""

    Private Sub cmdcancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            BILLNO = gridrec.GetFocusedRowCellValue("SRNO")
            Me.Close()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub SelectBills_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Or (e.KeyCode = Keys.X And e.Alt = True) Then
                Me.Close()
            ElseIf e.KeyCode = Keys.E And e.Alt = True Then
                cmdok_Click(sender, e)
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid(ByVal tepmcondition)
        Try
            Dim OBJCMN As New ClsCommon
            Dim dt As DataTable = OBJCMN.search(" * ", "", " (SELECT OPENINGBILL.BILL_INITIALS AS SRNO, LEDGERS.Acc_cmpname AS NAME, OPENINGBILL.BILL_AMT AS BILLAMT, OPENINGBILL.BILL_BALANCE AS BALAMT, 'OPENING' AS TYPE, OPENINGBILL.BILL_INITIALS AS REFNO, OPENINGBILL.BILL_NO AS BILLNO, OPENINGBILL.BILL_DATE AS DATE, OPENINGBILL.BILL_CMPID AS CMPID, OPENINGBILL.BILL_LOCATIONID AS LOCATIONID, OPENINGBILL.BILL_YEARID AS YEARID FROM OPENINGBILL INNER JOIN LEDGERS ON OPENINGBILL.BILL_LEDGERID = LEDGERS.Acc_id AND OPENINGBILL.BILL_CMPID = LEDGERS.Acc_cmpid AND OPENINGBILL.BILL_LOCATIONID = LEDGERS.Acc_locationid And OPENINGBILL.BILL_YEARID = LEDGERS.Acc_yearid WHERE(OPENINGBILL.BILL_YEARID = " & YearId & ") UNION ALL  SELECT INVOICEMASTER.INVOICE_INITIALS AS SRNO, LEDGERS.Acc_cmpname AS NAME, INVOICEMASTER.INVOICE_GRANDTOTAL AS BILLAMT, INVOICEMASTER.INVOICE_BALANCE AS BALAMT, 'INVOICE' AS TYPE, '' AS REFNO, CAST(INVOICEMASTER.INVOICE_NO AS VARCHAR(50)) AS BILLNO, INVOICEMASTER.INVOICE_DATE AS DATE, INVOICEMASTER.INVOICE_CMPID AS CMPID, INVOICEMASTER.INVOICE_LOCATIONID AS LOCATIONID, INVOICEMASTER.INVOICE_YEARID AS YEARID FROM INVOICEMASTER INNER JOIN LEDGERS ON INVOICEMASTER.INVOICE_LEDGERID = LEDGERS.Acc_id AND INVOICEMASTER.INVOICE_CMPID = LEDGERS.Acc_cmpid AND INVOICEMASTER.INVOICE_LOCATIONID = LEDGERS.Acc_locationid And INVOICEMASTER.INVOICE_YEARID = LEDGERS.Acc_yearid WHERE INVOICEMASTER.INVOICE_YEARID = " & YearId & " UNION ALL SELECT PURCHASEMASTER.BILL_INITIALS AS SRNO, LEDGERS.Acc_cmpname AS NAME, (CASE WHEN BILL_RCM = 1 THEN BILL_SUBTOTAL ELSE PURCHASEMASTER.BILL_GRANDTOTAL END) AS BILLAMT, PURCHASEMASTER.BILL_BALANCE AS BALAMT, 'PURCHASE' AS TYPE, PURCHASEMASTER.BILL_PARTYBILLNO AS REFNO, CAST(PURCHASEMASTER.BILL_NO  AS VARCHAR(50)) AS BILLNO, PURCHASEMASTER.BILL_DATE AS DATE, PURCHASEMASTER.BILL_CMPID AS CMPID, PURCHASEMASTER.BILL_LOCATIONID AS LOCATIONID, PURCHASEMASTER.BILL_YEARID AS YEARID FROM PURCHASEMASTER INNER JOIN LEDGERS ON PURCHASEMASTER.BILL_LEDGERID = LEDGERS.Acc_id AND PURCHASEMASTER.BILL_CMPID = LEDGERS.Acc_cmpid AND PURCHASEMASTER.BILL_LOCATIONID = LEDGERS.Acc_locationid And PURCHASEMASTER.BILL_YEARID = LEDGERS.Acc_yearid WHERE PURCHASEMASTER.BILL_YEARID = " & YearId & " UNION ALL SELECT NONPURCHASE.NP_INITIALS AS SRNO, LEDGERS.Acc_cmpname AS NAME, (CASE WHEN NP_RCM = 1 THEN NP_TOTALTAXABLEAMT ELSE NONPURCHASE.NP_GRANDTOTAL END) AS BILLAMT, NONPURCHASE.NP_BALANCE AS BALAMT, 'EXPENSE' AS TYPE, NONPURCHASE.NP_PARTYBILLNO AS REFNO, CAST(NONPURCHASE.NP_NO  AS VARCHAR(50)) AS BILLNO, NONPURCHASE.NP_DATE AS DATE, NONPURCHASE.NP_CMPID AS CMPID, 0 AS LOCATIONID, NONPURCHASE.NP_YEARID AS YEARID FROM NONPURCHASE INNER JOIN LEDGERS ON NONPURCHASE.NP_LEDGERID = LEDGERS.Acc_id WHERE NONPURCHASE.NP_YEARID = " & YearId & " UNION ALL SELECT CREDITNOTEMASTER.CN_initials AS SRNO, LEDGERS.Acc_cmpname AS NAME, (CASE WHEN ISNULL(CN_RCM,0) = 'TRUE' THEN CN_SUBTOTAL ELSE CREDITNOTEMASTER.CN_GTOTAL END) AS BILLAMT, CREDITNOTEMASTER.CN_BALANCE AS BALAMT, 'CREDITNOTE' AS TYPE, CREDITNOTEMASTER.CN_PARTYREFNO AS REFNO, CREDITNOTEMASTER.CN_NO AS BILLNO, CREDITNOTEMASTER.CN_date AS DATE, CREDITNOTEMASTER.CN_CMPID AS CMPID, CREDITNOTEMASTER.CN_LOCATIONID AS LOCATIONID, CREDITNOTEMASTER.CN_YEARID AS YEARID FROM CREDITNOTEMASTER INNER JOIN LEDGERS ON CREDITNOTEMASTER.CN_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN CREDITNOTEMASTER_BILLDESC ON CREDITNOTEMASTER.CN_NO = CREDITNOTEMASTER_BILLDESC.CN_NO AND CREDITNOTEMASTER.CN_registerid = CREDITNOTEMASTER_BILLDESC.CN_REGISTERID WHERE CREDITNOTEMASTER.CN_BALANCE > 0 AND CN_date >= '07/01/2017'AND CN_BILLNO = '' AND CREDITNOTEMASTER_BILLDESC.CN_NO IS NULL UNION ALL SELECT CREDITNOTEMASTER.CN_initials AS SRNO, LEDGERS.Acc_cmpname AS NAME, CREDITNOTEMASTER_BILLDESC.CN_AMT AS BILLAMT, CREDITNOTEMASTER_BILLDESC.CN_BALANCE AS BALAMT, 'CREDITNOTE' AS TYPE, CREDITNOTEMASTER.CN_PARTYREFNO AS REFNO, CREDITNOTEMASTER.CN_NO AS BILLNO, CREDITNOTEMASTER.CN_date AS DATE, CREDITNOTEMASTER.CN_CMPID AS CMPID, CREDITNOTEMASTER.CN_LOCATIONID AS LOCATIONID, CREDITNOTEMASTER.CN_YEARID AS YEARID FROM CREDITNOTEMASTER INNER JOIN LEDGERS ON CREDITNOTEMASTER.CN_LEDGERID = LEDGERS.Acc_id INNER JOIN CREDITNOTEMASTER_BILLDESC ON CREDITNOTEMASTER.CN_NO = CREDITNOTEMASTER_BILLDESC.CN_NO AND CREDITNOTEMASTER.CN_registerid = CREDITNOTEMASTER_BILLDESC.CN_REGISTERID WHERE CREDITNOTEMASTER_BILLDESC.CN_BALANCE > 0 AND CREDITNOTEMASTER_BILLDESC.CN_PAYTYPE = 'New Ref' UNION ALL SELECT DEBITNOTEMASTER.DN_initials AS SRNO, LEDGERS.Acc_cmpname AS NAME, DEBITNOTEMASTER.DN_GTOTAL AS BILLAMT, DEBITNOTEMASTER.DN_BALANCE AS BALAMT, 'DEBITNOTE' AS TYPE, DEBITNOTEMASTER.DN_initials AS REFNO, DEBITNOTEMASTER.DN_NO AS BILLNO, DEBITNOTEMASTER.DN_date AS DATE, DEBITNOTEMASTER.DN_CMPID AS CMPID, DEBITNOTEMASTER.DN_LOCATIONID AS LOCATIONID, DEBITNOTEMASTER.DN_YEARID AS YEARID FROM DEBITNOTEMASTER INNER JOIN LEDGERS ON DEBITNOTEMASTER.DN_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN DEBITNOTEMASTER_BILLDESC ON DEBITNOTEMASTER.DN_NO = DEBITNOTEMASTER_BILLDESC.DN_NO AND DEBITNOTEMASTER.DN_registerid = DEBITNOTEMASTER_BILLDESC.DN_REGISTERID WHERE DEBITNOTEMASTER.DN_BALANCE > 0 AND DN_date >= '07/01/2017' AND DN_BILLNO = '' AND DEBITNOTEMASTER_BILLDESC.DN_NO IS NULL UNION ALL SELECT DEBITNOTEMASTER.DN_initials AS SRNO, LEDGERS.Acc_cmpname AS NAME, DEBITNOTEMASTER_BILLDESC.DN_AMT AS BILLAMT, DEBITNOTEMASTER_BILLDESC.DN_BALANCE AS BALAMT, 'DEBITNOTE' AS TYPE, DEBITNOTEMASTER.DN_initials AS REFNO, DEBITNOTEMASTER.DN_NO AS BILLNO, DEBITNOTEMASTER.DN_date AS DATE, DEBITNOTEMASTER.DN_CMPID AS CMPID, DEBITNOTEMASTER.DN_LOCATIONID AS LOCATIONID, DEBITNOTEMASTER.DN_YEARID AS YEARID FROM DEBITNOTEMASTER INNER JOIN LEDGERS ON DEBITNOTEMASTER.DN_LEDGERID = LEDGERS.Acc_id INNER JOIN DEBITNOTEMASTER_BILLDESC ON DEBITNOTEMASTER.DN_NO = DEBITNOTEMASTER_BILLDESC.DN_NO AND DEBITNOTEMASTER.DN_registerid = DEBITNOTEMASTER_BILLDESC.DN_REGISTERID WHERE DEBITNOTEMASTER_BILLDESC.DN_BALANCE > 0 and DEBITNOTEMASTER_BILLDESC.DN_PAYTYPE = 'New Ref') AS T ", tepmcondition & " AND T.BALAMT > 0 AND T.YEARID =" & YearId & " ORDER BY T.TYPE, T.BILLNO ")
            griddetails.DataSource = dt
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub SelectBills_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Receipt.SELECTEDBILLNO = ""
            Dim CONDITION As String = ""
            If CMPNAME <> "" Then CONDITION = " AND T.NAME = '" & CMPNAME & "' "
            fillgrid(CONDITION)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridrec_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles gridrec.DoubleClick
        Try
            cmdok_Click(sender, e)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class