
Imports BL
Imports DevExpress.XtraEditors.Controls

Public Class PendingReturnDONo

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT

    Private Sub PendingReturnDONo_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub PendingReturnDONo_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Dim DTROW() As DataRow
            DTROW = USERRIGHTS.Select("FormName = 'GDN'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            FILLTRANS()
            fillgrid()

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLTRANS()
        Try
            CMBTRANSPORT.Items.Clear()
            Dim OBJCMN As New ClsCommon
            Dim DT As DataTable = OBJCMN.search("ACC_CMPNAME AS NAME", "", " LEDGERS INNER JOIN GROUPMASTER ON GROUP_ID = ACC_GROUPID  ", " AND GROUPMASTER.GROUP_SECONDARY = 'SUNDRY CREDITORS' AND ACC_TYPE = 'TRANSPORT' AND ACC_YEARID = " & YearId)
            If DT.Rows.Count > 0 Then
                For Each DTROW As DataRow In DT.Rows
                    CMBTRANSPORT.Items.Add(DTROW("NAME"))
                Next
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid()
        Try
            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If
            Dim WHERECLAUSE As String = ""
            'WE HAVE CHANGED THIS CODE, COZ WE NEED TO FETCH THE DATA FROM SALERETURN ALSO
            'If RBPENDING.Checked = True Then WHERECLAUSE = " AND ISNULL(GOODSRETURNMASTER.GR_RETURNDONO,'') = '' " Else WHERECLAUSE = " AND ISNULL(GOODSRETURNMASTER.GR_RETURNDONO,'') <> ''"
            If RBPENDING.Checked = True Then WHERECLAUSE = " AND T.RDONO = '' " Else WHERECLAUSE = " AND T.RDONO <> ''"

            Dim OBJCMN As New ClsCommonMaster
            'Dim dt As DataTable = OBJCMN.search(" ISNULL(GOODSRETURNMASTER.GR_NO, '') AS GRNO, GOODSRETURNMASTER.GR_DATE AS DATE, ISNULL(INVOICEMASTER.INVOICE_NO,0) AS INVOICENO, ISNULL(GODOWNMASTER.GODOWN_NAME, '') AS GODOWN, ISNULL(LEDGERS.ACC_CMPNAME,'') AS NAME, ISNULL(DYEINGLEDGERS.Acc_cmpname, '') AS DYEINGNAME, ISNULL(GOODSRETURNMASTER.GR_LOTNO, 0) AS LOTNO, ISNULL(GREYQUALITYMASTER.GREY_NAME, '') AS QUALITY, ISNULL(GOODSRETURNMASTER.GR_CHALLANTAKA, 0) AS CTAKA, ISNULL(GOODSRETURNMASTER.GR_CHALLANMTRS, 0) AS CMTRS, ISNULL(GOODSRETURNMASTER.GR_RETURNTAKA, 0) AS RTAKA, ISNULL(GOODSRETURNMASTER.GR_RETURNMTRS, 0) AS RMTRS, ISNULL(GOODSRETURNMASTER.GR_RETURNDONO, '') AS RDONO, ISNULL(GOODSRETURNMASTER.GR_SHORTAGE, 0) AS SHORTAGE, ISNULL(GOODSRETURNMASTER.GR_NETTTAKA, 0) AS NTAKA, ISNULL(GOODSRETURNMASTER.GR_NETTMTRS, 0) AS NMTRS, (CASE WHEN CAST(GOODSRETURNMASTER.GR_RETURNDATE AS DATE) = '' THEN NULL ELSE CAST(GOODSRETURNMASTER.GR_RETURNDATE AS DATE) END) AS RDATE, ISNULL(TRANSLEDGERS.ACC_CMPNAME ,'') AS TRANSNAME ", " ", "   GOODSRETURNMASTER INNER JOIN GODOWNMASTER ON GOODSRETURNMASTER.GR_GODOWNID = GODOWNMASTER.GODOWN_ID INNER JOIN GREYQUALITYMASTER ON GOODSRETURNMASTER.GR_GREYQUALITYID = GREYQUALITYMASTER.GREY_ID INNER JOIN LEDGERS ON GOODSRETURNMASTER.GR_LEDGERID = LEDGERS.Acc_id INNER JOIN LEDGERS AS DYEINGLEDGERS ON GOODSRETURNMASTER.GR_DYEINGID = DYEINGLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON GOODSRETURNMASTER.GR_TRANSID = TRANSLEDGERS.Acc_id LEFT OUTER JOIN INVOICEMASTER INNER JOIN INVOICEMASTER_DESC ON INVOICEMASTER.INVOICE_NO = INVOICEMASTER_DESC.INVOICE_NO AND INVOICEMASTER.INVOICE_REGISTERID = INVOICEMASTER_DESC.INVOICE_REGISTERID ON GOODSRETURNMASTER.GR_DYEINGID = INVOICEMASTER.INVOICE_DELIVERYID AND GOODSRETURNMASTER.GR_LOTNO = INVOICEMASTER_DESC.INVOICE_LOTNO", WHERECLAUSE & " AND (GOODSRETURNMASTER.GR_YEARID = '" & YearId & "') AND (GOODSRETURNMASTER.GR_LOTNO <> '') ORDER BY GOODSRETURNMASTER.GR_NO")
            Dim dt As DataTable = OBJCMN.search("*", "", " (SELECT DISTINCT ISNULL(GOODSRETURNMASTER.GR_NO, '') AS GRNO, GOODSRETURNMASTER.GR_DATE AS DATE, ISNULL(INVOICEMASTER.INVOICE_NO,0) AS INVOICENO, ISNULL(GODOWNMASTER.GODOWN_NAME, '') AS GODOWN, ISNULL(LEDGERS.ACC_CMPNAME,'') AS NAME, ISNULL(DYEINGLEDGERS.Acc_cmpname, '') AS DYEINGNAME, ISNULL(GOODSRETURNMASTER.GR_LOTNO, 0) AS LOTNO, ISNULL(GREYQUALITYMASTER.GREY_NAME, '') AS QUALITY, ISNULL(GOODSRETURNMASTER.GR_CHALLANTAKA, 0) AS CTAKA, ISNULL(GOODSRETURNMASTER.GR_CHALLANMTRS, 0) AS CMTRS, ISNULL(GOODSRETURNMASTER.GR_RETURNTAKA, 0) AS RTAKA, ISNULL(GOODSRETURNMASTER.GR_RETURNMTRS, 0) AS RMTRS, ISNULL(GOODSRETURNMASTER.GR_RETURNDONO, '') AS RDONO, ISNULL(GOODSRETURNMASTER.GR_SHORTAGE, 0) AS SHORTAGE, ISNULL(GOODSRETURNMASTER.GR_NETTTAKA, 0) AS NTAKA, ISNULL(GOODSRETURNMASTER.GR_NETTMTRS, 0) AS NMTRS, (CASE WHEN CAST(GOODSRETURNMASTER.GR_RETURNDATE AS DATE) = '' THEN NULL ELSE CAST(GOODSRETURNMASTER.GR_RETURNDATE AS DATE) END) AS RDATE, ISNULL(TRANSLEDGERS.ACC_CMPNAME ,'') AS TRANSNAME, 'GR' AS TYPE FROM GOODSRETURNMASTER INNER JOIN GODOWNMASTER ON GOODSRETURNMASTER.GR_GODOWNID = GODOWNMASTER.GODOWN_ID INNER JOIN GREYQUALITYMASTER ON GOODSRETURNMASTER.GR_GREYQUALITYID = GREYQUALITYMASTER.GREY_ID INNER JOIN LEDGERS ON GOODSRETURNMASTER.GR_LEDGERID = LEDGERS.Acc_id INNER JOIN LEDGERS AS DYEINGLEDGERS ON GOODSRETURNMASTER.GR_DYEINGID = DYEINGLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON GOODSRETURNMASTER.GR_TRANSID = TRANSLEDGERS.Acc_id LEFT OUTER JOIN INVOICEMASTER INNER JOIN INVOICEMASTER_DESC ON INVOICEMASTER.INVOICE_NO = INVOICEMASTER_DESC.INVOICE_NO AND INVOICEMASTER.INVOICE_REGISTERID = INVOICEMASTER_DESC.INVOICE_REGISTERID ON GOODSRETURNMASTER.GR_DYEINGID = INVOICEMASTER.INVOICE_DELIVERYID AND GOODSRETURNMASTER.GR_LOTNO = INVOICEMASTER_DESC.INVOICE_LOTNO WHERE GOODSRETURNMASTER.GR_YEARID = " & YearId & " AND (GOODSRETURNMASTER.GR_LOTNO <> '') UNION ALL SELECT ISNULL(SALERETURN.SALRET_NO, '') AS GRNO, SALERETURN.SALRET_DATE AS DATE, ISNULL(INVOICEMASTER.INVOICE_NO, 0) AS INVOICENO, ISNULL(GODOWNMASTER.GODOWN_NAME, '') AS GODOWN, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(DYEINGLEDGERS.Acc_cmpname, '') AS DYEINGNAME, ISNULL(SALERETURN_DESC.SALRET_LOTNO, 0) AS LOTNO, ISNULL(GREYQUALITYMASTER.GREY_NAME, '') AS QUALITY, ISNULL(INVOICEMASTER.INVOICE_TOTALPCS, 0) AS CTAKA, ISNULL(INVOICEMASTER.INVOICE_TOTALMTRS, 0) AS CMTRS, SUM(ISNULL(SALERETURN_DESC.SALRET_PCS, 0)) AS RTAKA, SUM(ISNULL(SALERETURN_DESC.SALRET_MTRS, 0)) AS RMTRS, ISNULL(SALERETURN.SALRET_DONO, '') AS RDONO, ISNULL(SALERETURN.SALRET_SHORTAGE, 0) AS SHORTAGE, ISNULL(SALERETURN.SALRET_NETTTAKA, 0) AS NTAKA, ISNULL(SALERETURN.SALRET_NETTMTRS, 0) AS NMTRS, CAST(SALERETURN.SALRET_DATE AS DATE) AS RDATE, ISNULL(TRANSLEDGERS.Acc_cmpname, '') AS TRANSNAME, 'SALRET' AS TYPE FROM SALERETURN INNER JOIN SALERETURN_DESC ON SALERETURN.SALRET_NO = SALERETURN_DESC.SALRET_NO AND SALERETURN.SALRET_REGISTERID = SALERETURN_DESC.SALRET_REGISTERID AND SALERETURN.SALRET_YEARID = SALERETURN_DESC.SALRET_YEARID INNER JOIN GODOWNMASTER ON SALERETURN.SALRET_GODOWNID = GODOWNMASTER.GODOWN_ID INNER JOIN GREYQUALITYMASTER ON SALERETURN_DESC.SALRET_QUALITYID = GREYQUALITYMASTER.GREY_ID INNER JOIN LEDGERS ON SALERETURN.SALRET_LEDGERID = LEDGERS.Acc_id INNER JOIN LEDGERS AS DYEINGLEDGERS ON SALERETURN.SALRET_DYEINGID = DYEINGLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON SALERETURN.SALRET_TRANSID = TRANSLEDGERS.Acc_id INNER JOIN INVOICEMASTER ON SALERETURN.SALRET_INVOICENO = INVOICEMASTER.INVOICE_NO AND SALERETURN.SALRET_INVOICEREGID = INVOICEMASTER.INVOICE_REGISTERID AND SALERETURN.SALRET_YEARID = INVOICEMASTER.INVOICE_YEARID WHERE SALERETURN.SALRET_YEARID = " & YearId & " AND ISNULL(INVOICEMASTER.INVOICE_NOGR,'FALSE') = 'FALSE' GROUP BY ISNULL(SALERETURN.SALRET_NO, ''), SALERETURN.SALRET_DATE, ISNULL(INVOICEMASTER.INVOICE_NO, 0), ISNULL(GODOWNMASTER.GODOWN_NAME, ''), ISNULL(LEDGERS.Acc_cmpname, ''), ISNULL(DYEINGLEDGERS.Acc_cmpname, ''), ISNULL(SALERETURN_DESC.SALRET_LOTNO, 0), ISNULL(GREYQUALITYMASTER.GREY_NAME, ''), ISNULL(INVOICEMASTER.INVOICE_TOTALPCS, 0), ISNULL(INVOICEMASTER.INVOICE_TOTALMTRS, 0), ISNULL(SALERETURN.SALRET_DONO, ''), ISNULL(SALERETURN.SALRET_SHORTAGE, 0), ISNULL(SALERETURN.SALRET_NETTTAKA, 0), ISNULL(SALERETURN.SALRET_NETTMTRS, 0), CAST(SALERETURN.SALRET_DATE AS DATE), ISNULL(TRANSLEDGERS.Acc_cmpname, '') ) AS T", WHERECLAUSE & " ORDER BY T.GRNO ")
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub showform(ByVal editval As Boolean, ByVal GRNO As Integer)
        Try
            If (editval = True And USEREDIT = False And USERVIEW = False) Or (editval = False And USERADD = False) Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If

            If (editval = False) Or (editval = True And gridbill.RowCount > 0) Then
                Dim OBJGRNO As New GoodsReturn
                OBJGRNO.MdiParent = MDIMain
                OBJGRNO.EDIT = editval
                OBJGRNO.TEMPGRNO = GRNO
                OBJGRNO.Show()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdcancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Private Sub gridbilldetails_DoubleClick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles gridbilldetails.DoubleClick
        Try
            showform(True, gridbill.GetFocusedRowCellValue("SRNO"))
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDREFRESH_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDREFRESH.Click
        Try
            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDOK_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDOK.Click
        Try
            Dim ROW As DataRow = gridbill.GetFocusedDataRow
            If ROW Is Nothing Then Exit Sub
            Dim OBJCMN As New ClsCommon
            Dim DT As New DataTable

            If ROW("RDONO") <> "" Then
                If ROW("TYPE") = "GR" Then DT = OBJCMN.Execute_Any_String("UPDATE GOODSRETURNMASTER SET GR_RETURNDONO = '" & ROW("RDONO") & "' WHERE GR_NO = " & Val(ROW("GRNO")) & " AND GR_YEARID = " & YearId, "", "")
                If ROW("TYPE") = "SALRET" Then DT = OBJCMN.Execute_Any_String("UPDATE SALERETURN SET SALRET_DONO = '" & ROW("RDONO") & "' WHERE SALRET_NO = " & Val(ROW("GRNO")) & " AND SALRET_YEARID = " & YearId, "", "")
                DT = OBJCMN.Execute_Any_String("UPDATE INVOICEMASTER SET INVOICEMASTER.INVOICE_GRNO = '" & ROW("RDONO") & "' FROM INVOICEMASTER INNER JOIN INVOICEMASTER_DESC ON INVOICEMASTER.INVOICE_NO = INVOICEMASTER_DESC.INVOICE_NO AND INVOICEMASTER.INVOICE_REGISTERID = INVOICEMASTER_DESC.INVOICE_REGISTERID INNER JOIN LEDGERS AS DYEINGLEDGERS ON INVOICE_DELIVERYID = DYEINGLEDGERS.ACC_ID WHERE INVOICEMASTER_DESC.INVOICE_LOTNO = " & ROW("LOTNO") & " AND DYEINGLEDGERS.ACC_CMPNAME = '" & ROW("DYEINGNAME") & "' AND INVOICEMASTER.INVOICE_YEARID = " & YearId, "", "")
            End If

            fillgrid()
            gridbill.Focus()

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_InvalidRowException(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Base.InvalidRowExceptionEventArgs) Handles gridbill.InvalidRowException
        e.ExceptionMode = ExceptionMode.NoAction
    End Sub

    Private Sub gridbill_ValidateRow(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Base.ValidateRowEventArgs) Handles gridbill.ValidateRow
        Try
            If IsDBNull(gridbill.GetRowCellValue(e.RowHandle, "RDONO")) = False Then If MsgBox("Save Entry?", MsgBoxStyle.YesNo) = MsgBoxResult.Yes Then Call CMDOK_Click(sender, e)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDDELETE_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDDELETE.Click
        Try

            Dim ROW As DataRow = gridbill.GetFocusedDataRow
            Dim OBJCMN As New ClsCommon
            Dim DT As New DataTable

            If IsDBNull(ROW("RDONO")) = True Then
                MsgBox("No Row To Delete")
                Exit Sub
            End If

            If MsgBox("Delete Data?", MsgBoxStyle.YesNo) = MsgBoxResult.No Then Exit Sub
            If ROW("TYPE") = "GR" Then DT = OBJCMN.Execute_Any_String("UPDATE GOODSRETURNMASTER SET GR_RETURNDONO = ''  WHERE GR_NO = " & Val(ROW("GRNO")) & " AND GR_YEARID = " & YearId, "", "")
            If ROW("TYPE") = "SALRET" Then DT = OBJCMN.Execute_Any_String("UPDATE SALERETURN SET SALRET_DONO = ''  WHERE SALRET_NO = " & Val(ROW("GRNO")) & " AND SALRET_YEARID = " & YearId, "", "")
            DT = OBJCMN.Execute_Any_String("UPDATE INVOICEMASTER SET INVOICEMASTER.INVOICE_GRNO = '' FROM INVOICEMASTER INNER JOIN INVOICEMASTER_DESC ON INVOICEMASTER.INVOICE_NO = INVOICEMASTER_DESC.INVOICE_NO AND INVOICEMASTER.INVOICE_REGISTERID = INVOICEMASTER_DESC.INVOICE_REGISTERID INNER JOIN LEDGERS AS DYEINGLEDGERS ON INVOICE_DELIVERYID = DYEINGLEDGERS.ACC_ID WHERE INVOICEMASTER_DESC.INVOICE_LOTNO = " & ROW("LOTNO") & " AND DYEINGLEDGERS.ACC_CMPNAME = '" & ROW("DYEINGNAME") & "' AND INVOICEMASTER.INVOICE_YEARID = " & YearId, "", "")
            fillgrid()
            gridbill.Focus()

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class