Imports BL

Public Class SelectInvoice

    Public DT As New DataTable
    Public PARTYNAME As String = ""  'for whereclause in fillgrid

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectGDN_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Windows.Forms.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectGDN_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Me.Top = 100
        fillgrid()
    End Sub

    Sub fillgrid(Optional ByVal where As String = "")
        Try
            Cursor.Current = Cursors.WaitCursor
            Dim OBJCMN As New ClsCommon
            ' DT = OBJCMN.search("CAST (0 AS BIT) AS CHK ,T.CHALLANNO,T.CHALLANDATE,T.NAME, T.AGENT,T.TRANSNAME,T.ORDERNO,T.ORDERDATE,T.TOTALTAKA,T.TOTALMTRS,T.CHALLANTYPE", "", " (SELECT     CHALLANMASTER.CHALLAN_NO AS CHALLANNO, CHALLANMASTER.CHALLAN_DATE AS CHALLANDATE, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(AGENT.Acc_cmpname, '') AS AGENT, ISNULL(TRANSPORT.Acc_cmpname, '') AS TRANSNAME, ISNULL(CHALLANMASTER.CHALLAN_ORDERNO, 0) AS ORDERNO, CHALLANMASTER.CHALLAN_ORDERDATE AS ORDERDATE, ISNULL(CHALLANMASTER.CHALLAN_TOTALTAKA, 0) AS TOTALTAKA, ISNULL(CHALLANMASTER.CHALLAN_TOTALMTRS, 0) AS TOTALMTRS, 'CHALLAN' AS CHALLANTYPE FROM CHALLANMASTER INNER JOIN LEDGERS ON CHALLANMASTER.CHALLAN_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSPORT ON CHALLANMASTER.CHALLAN_TRANSID = TRANSPORT.Acc_id LEFT OUTER JOIN LEDGERS AS AGENT ON CHALLANMASTER.CHALLAN_AGENTID = AGENT.Acc_id WHERE CHALLANMASTER.CHALLAN_DONE= 0 and LEDGERS.Acc_cmpname='" & PARTYNAME & "' AND CHALLANMASTER.CHALLAN_YEARID = " & YearId & " UNION ALL SELECT CHALLANFINISHMASTER.CHALLANFINISH_NO AS CHALLANNO, CHALLANFINISHMASTER.CHALLANFINISH_DATE AS DATE, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(AGENT.Acc_cmpname, '') AS AGENT, ISNULL(TRANSNAME.Acc_cmpname, '') AS TRANSNAME, CHALLANFINISHMASTER.CHALLANFINISH_ORDERNO AS ORDERNO, CHALLANFINISHMASTER.CHALLANFINISH_ORDERDATE AS ORDERDATE, ISNULL(CHALLANFINISHMASTER.CHALLANFINISH_TOTALTAKA, 0) AS TOTALTAKA, ISNULL(CHALLANFINISHMASTER.CHALLANFINISH_TOTALMTRS, 0) AS TOTALMTRS, 'CHALLANFINISHE' AS CHALLANTYPE FROM CHALLANFINISHMASTER INNER JOIN LEDGERS ON CHALLANFINISHMASTER.CHALLANFINISH_LEDGERID = LEDGERS.Acc_id INNER JOIN LEDGERS AS TRANSNAME ON CHALLANFINISHMASTER.CHALLANFINISH_TRANSID = TRANSNAME.Acc_id INNER JOIN LEDGERS AS AGENT ON CHALLANFINISHMASTER.CHALLANFINISH_AGENTID = AGENT.Acc_id WHERE CHALLANFINISHMASTER.CHALLANFINISH_DONE= 0 and LEDGERS.Acc_cmpname='" & PARTYNAME & "' AND CHALLANFINISHMASTER.CHALLANFINISH_YEARID = " & YearId & ") AS T ", "")
            Dim DT As DataTable = OBJCMN.search("CAST (0 AS BIT) AS CHK ,T.CHALLANNO,T.CHALLANDATE,T.NAME, T.AGENT,T.TRANSNAME,T.ORDERNO,T.ORDERSRNO,T.TOTALTAKA,T.TOTALMTRS,T.CHALLANTYPE, T.LOTNO, T.BALENO, T.DELIVERYAT ", "", " (SELECT CHALLANMASTER.CHALLAN_NO AS CHALLANNO, CHALLANMASTER.CHALLAN_DATE AS CHALLANDATE, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(DELIVERYLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(AGENT.Acc_cmpname, '') AS AGENT, ISNULL(TRANSPORT.Acc_cmpname, '') AS TRANSNAME, ISNULL(CHALLANMASTER.CHALLAN_ORDERNO, 0) AS ORDERNO,ISNULL(CHALLANMASTER.CHALLAN_ORDERSRNO, 0) AS ORDERSRNO,  ISNULL(CHALLANMASTER.CHALLAN_TOTALTAKA, 0) AS TOTALTAKA, ISNULL(CHALLANMASTER.CHALLAN_TOTALMTRS, 0) AS TOTALMTRS, 'CHALLAN' AS CHALLANTYPE , ISNULL(CHALLAN_LOTNO,0) AS LOTNO, '' AS BALENO FROM CHALLANMASTER INNER JOIN LEDGERS ON CHALLANMASTER.CHALLAN_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DELIVERYLEDGERS ON CHALLANMASTER.CHALLAN_DELIVERYID = DELIVERYLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSPORT ON CHALLANMASTER.CHALLAN_TRANSID = TRANSPORT.Acc_id LEFT OUTER JOIN LEDGERS AS AGENT ON CHALLANMASTER.CHALLAN_BROKERID = AGENT.Acc_id WHERE CHALLANMASTER.CHALLAN_DONE= 0 and CHALLANMASTER.CHALLAN_FORDYEING = 0 and LEDGERS.Acc_cmpname='" & PARTYNAME & "' AND CHALLANMASTER.CHALLAN_YEARID = " & YearId & " UNION ALL SELECT   DISTINCT  CHALLANFINISHMASTER.CHALLANFINISH_NO AS CHALLANNO, CHALLANFINISHMASTER.CHALLANFINISH_DATE AS DATE, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(DELIVERYLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(AGENT.Acc_cmpname, '') AS AGENT, ISNULL(TRANSNAME.Acc_cmpname, '') AS TRANSNAME, CHALLANFINISHMASTER.CHALLANFINISH_ORDERNO AS ORDERNO, ISNULL(CHALLANFINISHMASTER.CHALLANFINISH_ORDERSRNO, 0) AS ORDERSRNO, ISNULL(CHALLANFINISHMASTER.CHALLANFINISH_TOTALTAKA, 0) AS TOTALTAKA, ISNULL(CHALLANFINISHMASTER.CHALLANFINISH_TOTALMTRS, 0) AS TOTALMTRS, 'CHALLANFINISH' AS CHALLANTYPE, CHALLANFINISHMASTER_DESC.CHALLANFINISH_LOTNO, ISNULL(CHALLANFINISH_BALENO,'') AS BALENO FROM CHALLANFINISHMASTER INNER JOIN LEDGERS ON CHALLANFINISHMASTER.CHALLANFINISH_LEDGERID = LEDGERS.Acc_id INNER JOIN CHALLANFINISHMASTER_DESC ON CHALLANFINISHMASTER.CHALLANFINISH_NO = CHALLANFINISHMASTER_DESC.CHALLANFINISH_NO AND CHALLANFINISHMASTER.CHALLANFINISH_YEARID = CHALLANFINISHMASTER_DESC.CHALLANFINISH_YEARID LEFT OUTER JOIN LEDGERS AS TRANSNAME ON CHALLANFINISHMASTER.CHALLANFINISH_TRANSID = TRANSNAME.Acc_id LEFT OUTER JOIN LEDGERS AS DELIVERYLEDGERS ON CHALLANFINISHMASTER.CHALLANFINISH_DELIVERYID = DELIVERYLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS AGENT ON CHALLANFINISHMASTER.CHALLANFINISH_BROKERID = AGENT.Acc_id WHERE CHALLANFINISHMASTER.CHALLANFINISH_DONE= 0 and LEDGERS.Acc_cmpname='" & PARTYNAME & "' AND CHALLANFINISHMASTER.CHALLANFINISH_YEARID = " & YearId & ") AS T  ", "")
            gridbilldetails.DataSource = DT
            If DT.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click

    End Sub
End Class