
Imports BL
Imports DevExpress.XtraEditors.Controls

Public Class PendingGoodsReturn

    Public DT As New DataTable

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub PendingGoodsReturn_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Windows.Forms.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub PendingGoodsReturn_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid(ByVal WHERE As String)
        Try
            Cursor.Current = Cursors.WaitCursor
            Dim objclspreq As New ClsCommon()
            'Dim DT As DataTable = objclspreq.search(" ISNULL(CHALLANMASTER.CHALLAN_NO, 0) AS CHALLANNO, CHALLANMASTER.CHALLAN_DATE AS DATE, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(DELIVERYAT.Acc_cmpname, '') AS DELAT, ISNULL(CHALLANMASTER.CHALLAN_FORDYEING, 0) AS FORDYEING, ISNULL(GREYQUALITYMASTER.GREY_NAME, '') AS QUALITY, ISNULL(CHALLANMASTER.CHALLAN_TOTALTAKA, 0) AS TAKA, ISNULL(CHALLANMASTER.CHALLAN_TOTALMTRS, 0) AS MTRS, ISNULL(CHALLANMASTER.CHALLAN_LOTNO, 0) AS LOTNO", "", " CHALLANMASTER INNER JOIN CHALLANMASTER_DESC ON CHALLANMASTER.CHALLAN_NO = CHALLANMASTER_DESC.CHALLAN_NO AND  CHALLANMASTER.CHALLAN_YEARID = CHALLANMASTER_DESC.CHALLAN_YEARID INNER JOIN GREYQUALITYMASTER ON CHALLANMASTER_DESC.CHALLAN_QUALITYID = GREYQUALITYMASTER.GREY_ID INNER JOIN LEDGERS ON CHALLANMASTER.CHALLAN_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DELIVERYAT ON CHALLANMASTER.CHALLAN_DELIVERYID = DELIVERYAT.Acc_id", " ")
            'this code does not fetch data from openingstock grey with process
            'Dim DT As DataTable = objclspreq.search(" DISTINCT ISNULL(CHALLANMASTER.CHALLAN_NO, 0) AS CHALLANNO, CHALLANMASTER.CHALLAN_DATE AS DATE, ISNULL(INVOICE_NO,'') AS INVOICENO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(DELIVERYAT.Acc_cmpname, '') AS DELAT, ISNULL(CHALLANMASTER.CHALLAN_FORDYEING, 0) AS FORDYEING, ISNULL(GREYQUALITYMASTER.GREY_NAME, '') AS QUALITY, ISNULL(CHALLANMASTER.CHALLAN_TOTALTAKA, 0) AS TAKA, ISNULL(CHALLANMASTER.CHALLAN_TOTALMTRS, 0) AS MTRS, ISNULL(CHALLANMASTER.CHALLAN_LOTNO, 0) AS LOTNO", "", " CHALLANMASTER INNER JOIN CHALLANMASTER_DESC ON CHALLANMASTER.CHALLAN_NO = CHALLANMASTER_DESC.CHALLAN_NO AND  CHALLANMASTER.CHALLAN_YEARID = CHALLANMASTER_DESC.CHALLAN_YEARID INNER JOIN GREYQUALITYMASTER ON CHALLANMASTER_DESC.CHALLAN_QUALITYID = GREYQUALITYMASTER.GREY_ID INNER JOIN LEDGERS ON CHALLANMASTER.CHALLAN_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DELIVERYAT ON CHALLANMASTER.CHALLAN_DELIVERYID = DELIVERYAT.Acc_id LEFT OUTER JOIN INVOICEMASTER_DESC ON INVOICE_FROMNO = CHALLANMASTER_DESC.CHALLAN_NO AND INVOICE_FROMSRNO = CHALLANMASTER_DESC.CHALLAN_GRIDSRNO AND INVOICEMASTER_DESC.INVOICE_YEARID = CHALLANMASTER_DESC.CHALLAN_YEARID AND INVOICE_GRIDTYPE = 'CHALLAN'", " AND ISNULL(CHALLANMASTER.CHALLAN_TYPE,'GREY') = 'GREY' AND CHALLANMASTER.CHALLAN_YEARID = " & YearId & " AND CHALLAN_LOTNO > 0 AND ISNULL(CHALLAN_NOGR,'FALSE') = 'FALSE' AND NOT EXISTS  (SELECT 1 FROM GOODSRETURNMASTER AS GR WHERE CHALLANMASTER.CHALLAN_DELIVERYID = GR.GR_DYEINGID AND CHALLANMASTER.CHALLAN_LOTNO = GR.GR_LOTNO AND GR.GR_YEARID = " & YearId & ")")
            Dim DT As DataTable = objclspreq.search(" * ", "", "(SELECT DISTINCT ISNULL(CHALLANMASTER.CHALLAN_NO, 0) AS CHALLANNO, CHALLANMASTER.CHALLAN_DATE AS DATE, ISNULL(INVOICE_NO,'') AS INVOICENO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(DELIVERYAT.Acc_cmpname, '') AS DELAT, ISNULL(CHALLANMASTER.CHALLAN_FORDYEING, 0) AS FORDYEING, ISNULL(GREYQUALITYMASTER.GREY_NAME, '') AS QUALITY, ISNULL(CHALLANMASTER.CHALLAN_TOTALTAKA, 0) AS TAKA, ISNULL(CHALLANMASTER.CHALLAN_TOTALMTRS, 0) AS MTRS, ISNULL(CHALLANMASTER.CHALLAN_LOTNO, 0) AS LOTNO FROM CHALLANMASTER INNER JOIN CHALLANMASTER_DESC ON CHALLANMASTER.CHALLAN_NO = CHALLANMASTER_DESC.CHALLAN_NO AND  CHALLANMASTER.CHALLAN_YEARID = CHALLANMASTER_DESC.CHALLAN_YEARID INNER JOIN GREYQUALITYMASTER ON CHALLANMASTER_DESC.CHALLAN_QUALITYID = GREYQUALITYMASTER.GREY_ID INNER JOIN LEDGERS ON CHALLANMASTER.CHALLAN_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DELIVERYAT ON CHALLANMASTER.CHALLAN_DELIVERYID = DELIVERYAT.Acc_id LEFT OUTER JOIN INVOICEMASTER_DESC ON INVOICE_FROMNO = CHALLANMASTER_DESC.CHALLAN_NO AND INVOICE_FROMSRNO = CHALLANMASTER_DESC.CHALLAN_GRIDSRNO AND INVOICEMASTER_DESC.INVOICE_YEARID = CHALLANMASTER_DESC.CHALLAN_YEARID AND INVOICE_GRIDTYPE = 'CHALLAN' WHERE ISNULL(CHALLANMASTER.CHALLAN_TYPE,'GREY') = 'GREY' AND CHALLANMASTER.CHALLAN_YEARID = " & YearId & " AND CHALLAN_LOTNO > 0 AND ISNULL(CHALLAN_NOGR,'FALSE') = 'FALSE' AND NOT EXISTS  (SELECT 1 FROM GOODSRETURNMASTER AS GR WHERE CHALLANMASTER.CHALLAN_DELIVERYID = GR.GR_DYEINGID AND CHALLANMASTER.CHALLAN_LOTNO = GR.GR_LOTNO AND GR.GR_YEARID = " & YearId & ") UNION ALL SELECT DISTINCT ISNULL(STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_NO, 0) AS CHALLANNO, YEARMASTER.year_startdate AS DATE, '' AS INVOICENO, '' AS NAME, ISNULL(DELIVERYAT.Acc_cmpname, '') AS DELAT, 0 AS FORDYEING, ISNULL(GREYQUALITYMASTER.GREY_NAME, '') AS QUALITY, ISNULL(STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_TAKA, 0) AS TAKA, ISNULL(STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_MTRS, 0) AS MTRS, ISNULL(STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_LOTNO, 0) AS LOTNO FROM STOCKMASTER_GREYPROCESSOR INNER JOIN YEARMASTER ON STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_YEARID = year_id INNER JOIN GREYQUALITYMASTER ON STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_GREYID = GREYQUALITYMASTER.GREY_ID LEFT OUTER JOIN LEDGERS AS DELIVERYAT ON STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_PROCESSORID = DELIVERYAT.Acc_id WHERE STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_YEARID = " & YearId & " AND STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_LOTNO > 0 AND NOT EXISTS  (SELECT 1 FROM GOODSRETURNMASTER AS GR WHERE STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_PROCESSORID = GR.GR_DYEINGID AND STOCKMASTER_GREYPROCESSOR.SMGREYPROCESSOR_LOTNO = GR.GR_LOTNO AND GR.GR_YEARID = " & YearId & ")) AS T", "")
            gridbilldetails.DataSource = DT
            If DT.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default
        End Try
    End Sub

    Private Sub gridbilldetails_DoubleClick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles gridbilldetails.DoubleClick
        Try
            Call cmdok_Click(sender, e)
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            DT.Columns.Add("DELAT")
            DT.Columns.Add("FORDYEING")
            DT.Columns.Add("QUALITY")
            DT.Columns.Add("TAKA")
            DT.Columns.Add("MTRS")
            DT.Columns.Add("LOTNO")
            DT.Columns.Add("NAME")

            Dim dtrow As DataRow = gridbill.GetFocusedDataRow
            DT.Rows.Add(dtrow("DELAT"), dtrow("FORDYEING"), dtrow("QUALITY"), dtrow("TAKA"), dtrow("MTRS"), dtrow("LOTNO"), dtrow("NAME"))

            Me.Close()

        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub
End Class